name: Pipeline
on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'scripts/**'
      - 'tests/**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing deps
        run: npm ci
      - name: Test
        run: npm run test
